[versions]
compileSdk = "31"
minSdk = "23"
targetSdk = "31"

agp = "7.1.3"
kotlin = "1.6.20"
compose = "1.2.0-alpha08"
activity-compose = "1.4.0"
compose_md3 = "1.0.0-alpha10"
androidx-navigation = "2.4.0-rc01"
retrofit = "2.9.0"
retrofit-logging = "5.0.0-alpha.3"
accompanist = "0.24.7-alpha"
coil = "1.4.0"
mmkv = "1.2.11"
dagger = "2.40.5"
moshi = "1.13.0"
androidx-lifecycle = "2.4.0"
androidx-paging = "3.1.1"
paging-compose = "1.0.0-alpha14"
ksp = "1.6.20-1.0.5"
exoplayer = "2.16.1"
media = "1.4.3"
kotlin-coroutines = "1.6.0"
androidx-core = "1.8.0-alpha04"
androidx-appcompat = "1.4.0"
androidx-material = "1.4.0"
hilt-viewmodel = "1.0.0-alpha03"
hilt = "1.0.0"
statusbar = "2.5.3"
permissionx = "1.6.1"
androidx-metrics = "1.0.0-alpha01"

[libraries]
gradleplugin-android = "com.android.tools.build:gradle:7.1.2"
gradleplugin-kotlin = "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10"
gradleplugin-dagger = "com.google.dagger:hilt-android-gradle-plugin:2.40.5"
#
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-material = { module = "com.google.android.material:material", version.ref = "androidx-material" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-metrics-performance = { module = "androidx.metrics:metrics-performance", version.ref = "androidx-metrics" }
androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }

compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-materila = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-materila3 = { module = "androidx.compose.material3:material3", version.ref = "compose_md3" }
compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }

navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
retrofit-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "retrofit-logging" }

moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-ksp = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-navigation-animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-navigation-material = { module = "com.google.accompanist:accompanist-navigation-material", version.ref = "accompanist" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }
accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }

coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

mmkv = { module = "com.tencent:mmkv-static", version.ref = "mmkv" }

dagger-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
hilt-viewmodel = { module = "androidx.hilt:hilt-lifecycle-viewmodel", version.ref = "hilt-viewmodel" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt" }
hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hilt" }

paging = { module = "androidx.paging:paging-runtime-ktx", version.ref = "androidx-paging" }
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging-compose" }

statusbar = { module = "cn.chitanda:dynamicstatusbar", version.ref = "statusbar" }

permissionx = { module = "com.guolindev.permissionx:permissionx", version.ref = "permissionx" }

androidx-media = { module = "androidx.media:media", version.ref = "media" }

exo-core = { module = "com.google.android.exoplayer:exoplayer-core", version.ref = "exoplayer" }
exo-ui = { module = "com.google.android.exoplayer:exoplayer-ui", version.ref = "exoplayer" }
exo-mediasession = { module = "com.google.android.exoplayer:extension-mediasession", version.ref = "exoplayer" }
exo-cast = { module = "com.google.android.exoplayer:extension-cast", version.ref = "exoplayer" }

kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlin-coroutines" }

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
android_app = {id = "com.android.application",version.ref = "agp"}
android_lib = {id = "com.android.library",version.ref = "agp"}